name: travel_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Functional programming in dart
  dartz: ^0.10.1

  # Simplify Equality Comparisons object
  equatable: ^2.0.5

  # Unit-Tests
  mockito: ^5.4.4

  # Remote fetch data or local store data
  dio: ^5.4.0
  data_connection_checker_nulls: ^0.0.2
  shared_preferences: ^2.2.2

  # state management


  # Internationalization and localization
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.0

  # service location
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  injectable: ^2.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  meta: ^1.10.0
  flutter_bloc: ^8.1.3



dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # how to set i on https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/travel_logo.svg
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Black.ttf
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/static/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/static/Inter-Light.ttf
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/static/Inter-Thin.ttf




