name: travel_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  collection: ^1.17.1
  expandable_text: ^2.3.0
  flutter_staggered_grid_view: ^0.4.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  validators: ^3.0.0
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1
  getwidget: ^3.1.1
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.2.6
  location: ^4.4.0
  get_it: ^7.6.0
  dio: ^5.1.2
  drift: ^2.8.0
  injectable: ^2.1.1
  path_provider: ^2.0.15
  path: ^1.8.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  time_picker_widget: ^1.0.0+10
  url_launcher: ^6.1.11
  flutter_sticky_header: ^0.6.5
  sticky_headers: ^0.3.0+2
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  sqlite3_flutter_libs: ^0.5.14
  go_router: ^7.0.0
  google_maps_flutter_web: ^0.4.0+8
  sliver_tools: ^0.2.10
  flutter_svg: ^2.0.5
  flutter_google_places_sdk: ^0.3.2+9
  google_geocoding_api: ^1.3.0
  app_tracking_transparency: ^2.0.4

  # Fire base plugin
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  firebase_crashlytics: ^3.3.0
  firebase_analytics: ^10.4.0
  firebase_performance: ^0.9.2+1

  expandable_page_view: ^1.0.17
  webview_flutter: ^4.2.0
  rxdart: ^0.27.7

  drift_db_viewer: 2.0.0
  badges: ^2.0.3
  package_info_plus: ^4.0.0
  flutter_widget_from_html_core: ^0.10.0
  pointer_interceptor: ^0.9.3+4
  firebase_performance_dio: ^0.5.0
  flutter_localization: ^0.1.11


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  #  test: ^1.22.0

  # lint: ^1.6.0 this package was modified by 'flutter_lints' on flutter 2.5.
  # how to set i on https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.1
  build_runner: ^2.4.2
  mobx_codegen: ^2.3.0
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  drift_dev: ^2.8.0
  mockito: ^5.4.0
  injectable_generator: ^2.1.5
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  build_web_compilers: ^4.0.3


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For details regarding how to use custom fonts in Flutter,
  # 1. Downloading the font file
  # 2. Importing the font files in a project
  # 3. Adding the font in the pubspec.yaml
  # 4. Using the font in an app
  #
  # or
  #
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Poppins
      fonts:

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Black.ttf
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
        - asset: assets/fonts/Inter/static/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/static/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/static/Inter-Light.ttf
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/static/Inter-Thin.ttf


