// Mocks generated by Mockito 5.4.4 from annotations
// in travel_app/test/features/flight_offer/presentation/flight_offers/flight_offers_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_app/core/errors/failure.dart' as _i6;
import 'package:travel_app/core/params/usecase.dart' as _i8;
import 'package:travel_app/core/presentation/input_converter.dart' as _i9;
import 'package:travel_app/features/flight_offer/data/models/flight_offer/flight_offer.dart'
    as _i7;
import 'package:travel_app/features/flight_offer/domain/repositories/flight_offer_repository.dart'
    as _i2;
import 'package:travel_app/features/flight_offer/domain/usecases/get_avaible_flights.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlightOfferRepository_0 extends _i1.SmartFake
    implements _i2.FlightOfferRepository {
  _FakeFlightOfferRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAvailableFlights].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAvailableFlights extends _i1.Mock
    implements _i4.GetAvailableFlights {
  MockGetAvailableFlights() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlightOfferRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFlightOfferRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FlightOfferRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.FlightOffer>> call(
          _i8.AvailableFlightParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.FlightOffer>>.value(
            _FakeEither_1<_i6.Failure, _i7.FlightOffer>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.FlightOffer>>);
}

/// A class which mocks [InputConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockInputConverter extends _i1.Mock implements _i9.InputConverter {
  MockInputConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Either<_i6.Failure, int> stringToInteger(String? str) =>
      (super.noSuchMethod(
        Invocation.method(
          #stringToInteger,
          [str],
        ),
        returnValue: _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #stringToInteger,
            [str],
          ),
        ),
      ) as _i3.Either<_i6.Failure, int>);
}
