// Mocks generated by Mockito 5.4.4 from annotations
// in travel_app/test/features/flight_offer/domain/usecases/get_available_flights_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_app/core/errors/failure.dart' as _i5;
import 'package:travel_app/features/flight_offer/domain/entities/flight_offer.dart'
    as _i6;
import 'package:travel_app/features/flight_offer/domain/repositories/flight_offer_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlightOfferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightOfferRepository extends _i1.Mock
    implements _i3.FlightOfferRepository {
  MockFlightOfferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FlightOffer>> getAvailableFlights(
    String? originLocationCode,
    String? destinationLocationCode,
    String? departureDate,
    String? adults,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableFlights,
          [
            originLocationCode,
            destinationLocationCode,
            departureDate,
            adults,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.FlightOffer>>.value(
            _FakeEither_0<_i5.Failure, _i6.FlightOffer>(
          this,
          Invocation.method(
            #getAvailableFlights,
            [
              originLocationCode,
              destinationLocationCode,
              departureDate,
              adults,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.FlightOffer>>);
}
